### PR TITLE
Travis and Composer Integration, some fixes

### PR DESCRIPTION
**Pull request by robo47**
For changes see complete commit message

To make it work nicely you would only have to merge it and create the package on
http://packagist.org/

Without packagist, there is no support for recursive requirements inside the other
librarys.

Will create composer-related pullrequests for mandango/mondator, mandango/mandango and fate/gravatar-php later, so the extra repository-declarations for those 3 requirements can be dropped from composer.json.

Travis-CI build can be seen here: http://travis-ci.org/#!/robo47/Silex-Extensions/builds/827860

### CODE REVIEW

**Comment by sveneisenschmidt** [comment]
@robo47 http://packagist.org/packages/fate/silex-extensions

**Comment by jwpage** [comment]
Should the `composer.json` require all the vendor packages, or simply mark them as suggested? 

For example, I'm only interested in using `AsseticExtension`, so I don't feel I should be required to install all the other packages too.

What are your thoughts on this?

**Comment by robo47** [comment]
I think that would be the better solution, will create a PR when I am back from holidays

**Comment by robo47** [comment]
PR is done: https://github.com/fate/Silex-Extensions/pull/17

**Pull request merged**
