### PR TITLE
Updated composer.json using suggest for used libraries

### PR DESCRIPTION
**Pull request by robo47**
Like suggested in https://github.com/fate/Silex-Extensions/pull/11#issuecomment-4628201

Using suggest for libraries

### CODE REVIEW

**Comment by jwpage** [comment]
+1, since I was the one who suggested it.

One thought though: should we be concerned about people who are already using "fate/silex-extensions" in their composer.json being bitten by the change?

**Comment by robo47** [comment]
I am no composer specialist, but I think since composer update uses the .lock file which should contain the packages already, it shouldn't uninstall them after an update.

**Comment by jwpage** [comment]
True, good point.

**Comment by sveneisenschmidt** [comment]
Thanks  @robo47

**Pull request merged**
